FROM alpine/git:latest AS checkout

RUN git clone https://github.com/kubernetes/test-infra /workspace/test-infra

FROM golang:alpine AS builder
ARG CMP_NAME

COPY --from=checkout /workspace/test-infra /workspace/test-infra
WORKDIR /workspace/test-infra/prow

RUN apk --no-cache add curl

RUN GOOS=linux GOARCH=arm GOARM=5 go build -ldflags="-w -s" -o /workspace/release/app ./cmd/${CMP_NAME}/
RUN if [ "$CMP_NAME" = "deck" ] ; then cp -r ./cmd/${CMP_NAME}/template /workspace/release/template ; fi

RUN if [ "$CMP_NAME" = "deck" ] ; then curl https://prow.k8s.io/static/command_help_bundle.min.js -o command_help_bundle.min.js ; fi
RUN if [ "$CMP_NAME" = "deck" ] ; then curl https://prow.k8s.io/static/plugin_help_bundle.min.js -o plugin_help_bundle.min.js ; fi
RUN if [ "$CMP_NAME" = "deck" ] ; then curl https://prow.k8s.io/static/pr_bundle.min.js -o pr_bundle.min.js ; fi
RUN if [ "$CMP_NAME" = "deck" ] ; then curl https://prow.k8s.io/static/prow_bundle.min.js -o prow_bundle.min.js ; fi
RUN if [ "$CMP_NAME" = "deck" ] ; then curl https://prow.k8s.io/static/spyglass_bundle.min.js -o spyglass_bundle.min.js ; fi
RUN if [ "$CMP_NAME" = "deck" ] ; then curl https://prow.k8s.io/static/spyglass_lens_bundle.min.js -o spyglass_lens_bundle.min.js ; fi
RUN if [ "$CMP_NAME" = "deck" ] ; then curl https://prow.k8s.io/static/tide_bundle.min.js -o tide_bundle.min.js ; fi
RUN if [ "$CMP_NAME" = "deck" ] ; then curl https://prow.k8s.io/static/tide_history_bundle.min.js -o tide_history_bundle.min.js ; fi

RUN if [ "$CMP_NAME" = "deck" ] ; then cp -r ./cmd/${CMP_NAME}/static /workspace/release/static ; fi

FROM alpine/git:latest
ARG CMP_NAME

COPY --from=builder /workspace/release/ /prow/
RUN if [ "$CMP_NAME" = "deck" ] ; then mv /prow/template /template ; fi
RUN if [ "$CMP_NAME" = "deck" ] ; then mv /prow/static /static ; fi

ENTRYPOINT [ "/prow/app" ]
